site_name: Arsenic Documentation

theme:
  name: material
  logo: img/PageLogo.png
  favicon: img/PageLogo.png
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - content.code.copy
  nav:
    - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg